// Date: 2023-9-24
// Author: Generated by GoCodeo.

const { isSafe } = require("../../../src/func/url");

test("Positive test case: Safe domain", () => {
    const url = "https://discord.com";
    const result = isSafe(url);
    expect(result).toBe(true);
});

test("Positive test case: Safe domain with www", () => {
    const url = "https://www.discord.com";
    const result = isSafe(url);
    expect(result).toBe(true);
});

// Negative test cases
test("Negative test case: Unsafe domain", () => {
    const url = "https://unsafe.com";
    const result = isSafe(url);
    expect(result).toBe(false);
});

test("Negative test case: Unsafe domain with www", () => {
    const url = "https://www.unsafe.com";
    const result = isSafe(url);
    expect(result).toBe(false);
});

// Edge test cases
test("Edge test case: Empty URL", () => {
    const url = "";
    const result = isSafe(url);
    expect(result).toBe(false);
});

test("Edge test case: Invalid URL", () => {
    const url = "invalid-url";
    const result = isSafe(url);
    expect(result).toBe(false);
});

test("Edge test case: URL without protocol", () => {
    const url = "discord.com";
    const result = isSafe(url);
    expect(result).toBe(false);
});

test("Edge test case: URL with invalid protocol", () => {
    const url = "ftp://discord.com";
    const result = isSafe(url);
    expect(result).toBe(false);
});

test("Edge test case: URL with subdomain", () => {
    const url = "https://subdomain.discord.com";
    const result = isSafe(url);
    expect(result).toBe(true);
});

test("Edge test case: URL with path", () => {
    const url = "https://discord.com/path";
    const result = isSafe(url);
    expect(result).toBe(true);
});
