// Date: 2023-9-24
// Author: Generated by GoCodeo.

const { BotCommandDeployment } = require("../../../src/entities/command");
const { getGuildId } = require("../../../src/events/ready");

describe("getGuildId", () => {
    const guildIds = {
        dev: "123",
        support: "456"
    };

    it("should return globalGuildId when deployment is Global", () => {
        const data = {
            deployment: BotCommandDeployment.Global
        };

        const result = getGuildId(data, guildIds);
        expect(result).toBe("0");
    });

    it("should return dev guildId when deployment is DevGuild", () => {
        const data = {
            deployment: BotCommandDeployment.DevGuild
        };

        const result = getGuildId(data, guildIds);
        expect(result).toBe("123");
    });

    it("should return support guildId when deployment is SupportGuild", () => {
        const data = {
            deployment: BotCommandDeployment.SupportGuild
        };

        const result = getGuildId(data, guildIds);
        expect(result).toBe("456");
    });

    it("should throw an error when deployment is unknown", () => {
        const data = {
            deployment: "Unknown"
        };

        expect(() => {
            getGuildId(data, guildIds);
        }).toThrow("Unknown BotCommandDeployment value: Unknown");
    });
});
